### ISSUE TITLE
Edición de Inventario

### ISSUE THREAD

**Issue by almacs** [almacs/Pretoria#11]
![image](https://cloud.githubusercontent.com/assets/9678980/6743393/f299349a-ce5e-11e4-97fe-834ee8314cba.png)

**Comment by almacs** [comment]
revisar la hoja de inventario desde donde se importo, para revisar que paso la ruta
Se agrego una condición para Molinos y ya no deben repetirse estos escenarios

**Comment by GabyBere** [comment]
Se necesitan el Escenario para su respectiva verificación.

**Comment by GabyBere** [comment]
ID: 16
Edición de Inventario
Resultado: Satisfactorio
1. Captura de un Molino solo contiene el campo Kg Base Seca.
![image](https://cloud.githubusercontent.com/assets/11563662/6759486/fc4a9f36-cf05-11e4-9b57-f266e71a2022.png)
1. Edición de un Molino de Esmalte, solo contiene el campo Kg Base Seca, después de exportar una Hoja Anterior
   ![image](https://cloud.githubusercontent.com/assets/11563662/6759569/9ac23430-cf06-11e4-9dce-385371475d7e.png)
