### ISSUE TITLE
Log de Reseteo de Contadores - Agregar Comentario

### ISSUE THREAD

**Issue by almacs** [almacs/Pretoria#13]
![image](https://cloud.githubusercontent.com/assets/9678980/6743446/9f5999ea-ce5f-11e4-8674-3f8ccc35ccfd.png)

**Comment by GabyBere** [comment]
No se encuentra las validación del comentario Obligatorio

**Comment by mtrejo30** [comment]
Se agrego validación no permitiendo avanzar sin la captura del comentario

**Comment by GabyBere** [comment]
Resultado: Satisfactorio

1 Al dar clic en el botón Guardar Contadores, aparece la ventana para agregar Comentarios.

![image](https://cloud.githubusercontent.com/assets/11563662/6871409/ef7c420c-d467-11e4-87f4-95f78bfc81b7.png)

2 Si el usuario intenta cerrar de la ventana sin agregar comentario, el sistema envía una alerta.

![image](https://cloud.githubusercontent.com/assets/11563662/6871422/0f7729fa-d468-11e4-8eb0-fac6e92327cd.png)
