### ISSUE TITLE
Inventarios - Captura de Numeros

### ISSUE THREAD

**Issue by almacs** [almacs/Pretoria#14]
![image](https://cloud.githubusercontent.com/assets/9678980/6743459/ba069b08-ce5f-11e4-838a-58068bc83068.png)

**Comment by GabyBere** [comment]
Resultado: Satisfactorio
1. Inventario Empaque y Embalaje 

Se realizó la verificación de las casillas numéricas del inventario y se comprobó que ya están funcionando de acuerdo a lo solicitado. 
        a. Muestra los ceros en las casillas
![image](https://cloud.githubusercontent.com/assets/11563662/6743716/458d27c0-ce63-11e4-9b86-4e806071d39a.png)
        b. Al dar clic se borra el cero y ya se puede agregar un valor.
       c. Se asigna el valor
![image](https://cloud.githubusercontent.com/assets/11563662/6743731/89b71154-ce63-11e4-879b-745e3d1beaa2.png)

**Comment by GabyBere** [comment]
Resultado: Satisfactorio
1. Inventario Materia Prima de Esmaltes

Se realizó la verificación de las casillas numéricas del inventario y se comprobó que ya están funcionando de acuerdo a lo solicitado. 
a. Muestra los ceros en las casillas
![image](https://cloud.githubusercontent.com/assets/11563662/6743790/4f1f5776-ce64-11e4-9d60-919980c8a792.png)
b. Al dar clic se borra el cero y ya se puede agregar un valor.
c. Se asigna el valor
![image](https://cloud.githubusercontent.com/assets/11563662/6743798/5d314554-ce64-11e4-83bf-07d20799ced5.png)
