### ISSUE TITLE
Nivel de vacio

### ISSUE THREAD

**Issue by GabyBere** [almacs/Pretoria#17]
No se puede agregar un nivel de Vacio.
Por automático se cambia a 0
![image](https://cloud.githubusercontent.com/assets/11563662/6756087/2c4962a8-ceed-11e4-985d-3685d10e8aff.png)

**Comment by mtrejo30** [comment]
Se reviso el JS

**Comment by mtrejo30** [comment]
Se necesitaba la información del material para permitir realizar el calculo
