### ISSUE TITLE
Reporte Tiempos Muertos - Por Causa (Grafica)

### ISSUE THREAD

**Issue by GabyBere** [almacs/Pretoria#19]
Esto sucede en la QA
![image](https://cloud.githubusercontent.com/assets/11563662/6787376/e5f802ba-d157-11e4-8242-6aacb14e1611.png)

**Comment by mtrejo30** [comment]
Validarlo

**Comment by edgar1090** [comment]
Al reproducir el escenario marca que se debe seleccionar una fecha, al seleccionar muestra bien el reporte
![image](https://cloud.githubusercontent.com/assets/11621492/6872891/e848f2e6-d471-11e4-9dbd-27e61993a318.png)
