### ISSUE TITLE
Posiciones duplicadas en Inventario

### ISSUE THREAD

**Issue by almacs** [almacs/Pretoria#2]
ID: 5
CC13
Causa: Se importó dos veces el inventario, ocasionando posiciones duplicadas. Propuesta para que se presenten estos incidentes.
![hoja anterior](https://cloud.githubusercontent.com/assets/11563662/6743208/b9c8d5be-ce5c-11e4-8fe5-af98c9743768.png)

**Comment by mtrejo30** [comment]
Liberado en QA

**Comment by GabyBere** [comment]
![image](https://cloud.githubusercontent.com/assets/11563662/6756662/ecc59efe-cef0-11e4-8c82-e8ad916b1713.png)

**Comment by mtrejo30** [comment]
Validar no estaba actualizado el SP

**Comment by GabyBere** [comment]
Resultado: Satisfactorio.
1. Se inicio con un inventario con 1 material, se le agrego una Hoja Anterior y el resultado fue que se reemplazan.
   ![image](https://cloud.githubusercontent.com/assets/11563662/6785091/3b92b760-d149-11e4-9088-5fbf37cf2694.png)
2. Nuevamente se agregan materiales de una Hoja Anterior, Fecha 05-02-15, con un total de 2 materiales y el resultado fue satisfactorio, ya que si se reemplazan.
   ![image](https://cloud.githubusercontent.com/assets/11563662/6785121/6f11e660-d149-11e4-9c4c-b5dcdb739bcb.png)
