### ISSUE TITLE
Reporte Tiempos Muertos - Por Causa- Productivo

### ISSUE THREAD

**Issue by GabyBere** [almacs/Pretoria#20]
![image](https://cloud.githubusercontent.com/assets/11563662/6787579/64bd414a-d159-11e4-9bdf-ed166eb142ce.png)

![image](https://cloud.githubusercontent.com/assets/11563662/6787573/5c30a03a-d159-11e4-9b6c-88bde635d62b.png)

**Comment by mtrejo30** [comment]
Debe ser por el mismo caso del 19

**Comment by edgar1090** [comment]
Escenario Satisfactorio
El error era que no mostraba el mensaje de favor de capturar fecha, ya muestra el mensaje y funcionalidad correcta
