### ISSUE TITLE
Validaciones de Energeticos

### ISSUE THREAD

**Issue by GabyBere** [almacs/Pretoria#21]
![image](https://cloud.githubusercontent.com/assets/9678980/6743272/53c1679e-ce5d-11e4-8799-783de8756d73.png)

Probar con excel que envio Ivan diferentes escenarios de captura de energeticos

**Comment by GabyBere** [comment]
Valores Anteriores

*Turno 1.
![image](https://cloud.githubusercontent.com/assets/11563662/6857616/b863956c-d3cd-11e4-98ec-a513dc20d3fa.png)

*Turno 2.

![image](https://cloud.githubusercontent.com/assets/11563662/6857632/cdaf687e-d3cd-11e4-8038-5fab3e3b2b02.png)

**Comment by GabyBere** [comment]
*Turno 3
Valores Correctos - Máximos

![image](https://cloud.githubusercontent.com/assets/11563662/6857642/f1d30472-d3cd-11e4-8ca2-29a919a0a867.png)

**Comment by GabyBere** [comment]
*Turno 3
Valores Fuera del Rango Permitido

![image](https://cloud.githubusercontent.com/assets/11563662/6857670/2d7f16be-d3ce-11e4-9c88-cd3cf8d2e987.png)

**Comment by edgar1090** [comment]
ESCENARIO 1
Se toma pantalla del Turno 1 y turno 2 para su verificacion 

![image](https://cloud.githubusercontent.com/assets/11621492/6858004/afe99dca-d3d0-11e4-9958-1e68e42a936f.png)

![image](https://cloud.githubusercontent.com/assets/11621492/6858011/bdb96d04-d3d0-11e4-9622-9991e143a7f6.png)

Se agrega el Turno 3 Verificando que el contador final deba ser igual o mayor al contador del turno 2

![image](https://cloud.githubusercontent.com/assets/11621492/6858081/6069954c-d3d1-11e4-8ba7-b03f3d0207ce.png)

Contador final con valores menores al contador del turno anterior no debe permitir 

![image](https://cloud.githubusercontent.com/assets/11621492/6858115/9a0b7c0c-d3d1-11e4-9497-a7e7da26c485.png)

Escenario satisfactorio

ESCENARIO 2
Se modifica el catalogo de la maquina el  Valor Max. Cont. Caudalimetro

![image](https://cloud.githubusercontent.com/assets/11621492/6858145/e113e576-d3d1-11e4-89c8-03a59f62576f.png)

Al modificarse el contador final del turno 3 se resetea y valor a permitir en el contador debe ser menor o igual a 288000

![image](https://cloud.githubusercontent.com/assets/11621492/6858169/1186f6d0-d3d2-11e4-8a3f-4b112a28bcbd.png)

Imagen del contador final con valor mayores al permitido 

![image](https://cloud.githubusercontent.com/assets/11621492/6858196/4a852cf4-d3d2-11e4-9ace-eb2ea48806e3.png)

Escenario Satisfactorio

ESCENARIO 3
El campo "Tiempo de Produccion" solo debe permitir valores de 0 a 480
El campo "Densidad Barbotina" solo debe permitir valores de 1.1 a 1.8

![image](https://cloud.githubusercontent.com/assets/11621492/6858264/b1766568-d3d2-11e4-8dcb-ee986a820059.png)

Valores incorrectos en los campos mencionados

![image](https://cloud.githubusercontent.com/assets/11621492/6858281/db1b737c-d3d2-11e4-8407-3f311abd908f.png)

Escenario Satisfactorio

ESCENARIO 4
Valores del Consumo Energetico estan en sus rangos correctos

![image](https://cloud.githubusercontent.com/assets/11621492/6858322/2fc1ee06-d3d3-11e4-8f6d-7f372d119ef2.png)

Valores del consumo energetico estan en rangos fuera de sus valores permitidos

![image](https://cloud.githubusercontent.com/assets/11621492/6858343/516219b4-d3d3-11e4-8398-f5ee8bb94ed0.png)

Escenario Satisfactorio
