### ISSUE TITLE
Validacion de caracteres 

### ISSUE THREAD

**Issue by edgar1090** [almacs/Pretoria#22]
Ruta: Configuracion - Catalogo de errores SAP

Campo "Encabezado" - Permite ingresar mas de 100 caracteres
Campo "Mensaje"  - Permite ingresar mas de 500 caracteres
Campo "Pie" - Solo permite 20 caracteres y deben de ser 100

**Comment by mtrejo30** [comment]
Validar

**Comment by edgar1090** [comment]
Resultado Satisfactorio
