### ISSUE TITLE
Catalogo de errores SAP- Boton Mostrar

### ISSUE THREAD

**Issue by edgar1090** [almacs/Pretoria#24]
Ruta: Configuracion - Catalogo de errores SAP

Muestra demasiadas veces su contenido al dar varios clic solo, deberia poder mostrarlo una vez

**Comment by mtrejo30** [comment]
Se agrego delay de 3 Seg

**Comment by edgar1090** [comment]
La funcionalidad se corrigió con el Explorador Internet Explorer pero sigue presentandose con Google Chrome

**Comment by mtrejo30** [comment]
Se cambio funcionalidad a hide pq chrome no lo respataba

**Comment by edgar1090** [comment]
En base a la nueva funcionalidad el
Escenario es Satisfactorio
