### ISSUE TITLE
Catalogo de errores SAP- ComboBox "Centro"

### ISSUE THREAD

**Issue by edgar1090** [almacs/Pretoria#25]
Al seleccionar un contenido diferente del ComboBox "Centro" y guardar, este no guarda el cambio

**Comment by mtrejo30** [comment]
Es funcionalidad, ya se deshabilito el drop en edición este solo es elegible en creación

**Comment by edgar1090** [comment]
En base al cambio de des-habilitar el campo centro el Escenario es Satisfactorio
