### ISSUE TITLE
Catalogo de Centro - Mensaje Informativo de Modificacion/Guardado

### ISSUE THREAD

**Issue by edgar1090** [almacs/Pretoria#28]
Ruta: Administracion - Catalogo de centros

 No hay mensaje informativo al modificar/guardar un valor del centro

**Comment by mtrejo30** [comment]
Es por funcionalidad, así lo podio el cliente

**Comment by edgar1090** [comment]
Por ordenes del usuario asi quedara esta funcionalidad
