### ISSUE TITLE
Catalogo de Turnos - Eliminar Turno

### ISSUE THREAD

**Issue by edgar1090** [almacs/Pretoria#29]
Ruta: Administracion - Catalogo de turnos

Marca error al eliminar un turno ya existente
(Si se crea uno este si es posible eliminarlo)

**Comment by mtrejo30** [comment]
Se hizo corrección, validar

**Comment by GabyBere** [comment]
Resultad: Satisfactorio.
![image](https://cloud.githubusercontent.com/assets/11563662/6851211/3d0c5356-d3a3-11e4-8e11-e9bd645f5dee.png)
