### ISSUE TITLE
Reporte Ejecutivo - Columna Enviado a SAP

### ISSUE THREAD

**Issue by almacs** [almacs/Pretoria#3]
ID:6 
CC14
1. Reporte  Ejecutivo, mostrar únicamente el Inventario Cero enviado a SAP, no el generado.

**Comment by edgar1090** [comment]
Escenario Satisfactorio
![image](https://cloud.githubusercontent.com/assets/11621492/6877544/7d12673e-d497-11e4-8802-2afb778acd18.png)
