### ISSUE TITLE
Administracion de perfiles - Eliminar perfil

### ISSUE THREAD

**Issue by edgar1090** [almacs/Pretoria#31]
Ruta: Administracion - Administracion de perfiles

NO permite eliminar un perfil

**Comment by mtrejo30** [comment]
Se hizo corrección, validar

**Comment by GabyBere** [comment]
Resultado: Satisfactorio

![image](https://cloud.githubusercontent.com/assets/11563662/6851703/3ffbde08-d3a6-11e4-8100-aca10f6f4394.png)
