### ISSUE TITLE
Administracion de perfiles - Busqueda de perfiles

### ISSUE THREAD

**Issue by edgar1090** [almacs/Pretoria#32]
Ruta: Administracion - Administracion de perfiles

En la busqueda de perfiles la opcion "Seleccione" y "Todos" hacen la misma funcion

**Comment by mtrejo30** [comment]
Se hizo corrección, validar (se elimino el todos)

**Comment by GabyBere** [comment]
Resultado: Satisfactorio

![image](https://cloud.githubusercontent.com/assets/11563662/6851604/c40d7a22-d3a5-11e4-8b76-7a5b2976110e.png)
