### ISSUE TITLE
Catalogo de Grupo de Articulos - Barra de desplazamiento

### ISSUE THREAD

**Issue by edgar1090** [almacs/Pretoria#34]
Ruta: Configuracion - Catalogo de Grupo de articulos

Al seleccionar el checkbox "Es Serigrafaria" desaparece la barra de desplazamiento y no permite ver los demas grupos de articulos

**Comment by mtrejo30** [comment]
Actualizado

**Comment by edgar1090** [comment]
Escenario Satisfactorio
