### ISSUE TITLE
Catalogo de Grupo de Articulos - Paginacion

### ISSUE THREAD

**Issue by edgar1090** [almacs/Pretoria#35]
Ruta: Configuracion - Catalogo de Grupo de articulos

No sirve la paginacion de Grid

**Comment by mtrejo30** [comment]
Se hizo corrección, validar

**Comment by edgar1090** [comment]
Resultado satisfactorio
![pginacion](https://cloud.githubusercontent.com/assets/11621492/6851582/a5b89b10-d3a5-11e4-8f9f-54e59536515f.jpg)
