### ISSUE TITLE
Modulo de Recipientes - Modificación de recipiente

### ISSUE THREAD

**Issue by edgar1090** [almacs/Pretoria#36]
Ruta: Configuracion - Modulo de recipientes

Al realizar una modificación en el campo "Orden Aparición"  en cualquiera de los registro, este filtra el registro mas abajo en la paginacion y ya no lo ordena por orden alfabético.

**Comment by mtrejo30** [comment]
Funcionalidad, el orden ayuda en el ordenamiento

**Comment by edgar1090** [comment]
Se pregunto al usuario y comento que la funcionalidad se encuentra correcta
