### ISSUE TITLE
Modulo de Recipientes - Eliminacion de recipiente

### ISSUE THREAD

**Issue by edgar1090** [almacs/Pretoria#37]
Ruta: Configuracion - Modulo de Recipiente

No permite eliminar un registro marca error.
( Cuando se crea una nuevo este si lo permite eliminar )

**Comment by mtrejo30** [comment]
Se modifico el mensaje

**Comment by edgar1090** [comment]
Muestra mensaje informativo de que no es posible eliminar el recipiente.
Escenario Satisfactorio
