### ISSUE TITLE
Error al Crear Nuevo

### ISSUE THREAD

**Issue by GabyBere** [almacs/Pretoria#38]
![image](https://cloud.githubusercontent.com/assets/11563662/6851338/0e14abf6-d3a4-11e4-9ceb-60125ba3ee78.png)

**Comment by GabyBere** [comment]
Sigue apareciendo.

**Comment by mtrejo30** [comment]
No puedo replicarlo, favor de volverlo a validar

**Comment by edgar1090** [comment]
No se puede replicar el escenario
Si es posible Crear una nueva existecia
