### ISSUE TITLE
Modulo de Maquinas - Consulta de Maquina(Porcelanite)

### ISSUE THREAD

**Issue by edgar1090** [almacs/Pretoria#40]
Ruta: Configuración - Modulo de Maquinas

Las maquinas del Centro "Porcelanite Lamosa Valle Ote." marca error al consultar su informacion
(Para todas las demás maquinas de los centro esta correcto)

**Comment by mtrejo30** [comment]
Validar el cambio

**Comment by edgar1090** [comment]
Escenario Satisfactorio
