### ISSUE TITLE
Modulo de Perfil

### ISSUE THREAD

**Issue by GabyBere** [almacs/Pretoria#42]
Verificar por que no se puede editar.

![image](https://cloud.githubusercontent.com/assets/11563662/6853151/050ed54e-d3af-11e4-8423-19900a68f44d.png)

**Comment by mtrejo30** [comment]
Validar

**Comment by edgar1090** [comment]
Escenario Satisfactorio
Ya permite editar el admistrador local

![image](https://cloud.githubusercontent.com/assets/11621492/6878003/bb7d4d18-d49c-11e4-9c4f-4a71d0e8e5ad.png)
