### ISSUE TITLE
Configuracion Motivo de Paro - Informacion repetida

### ISSUE THREAD

**Issue by edgar1090** [almacs/Pretoria#43]
Ruta: Configuración - Catalogo Motivo de Paro

La columna "Centro" tiene repetida la información de la columna "Motivo"
(La columna centro debe tener el nombre del centro de donde se hizo de motivo de paro)

**Comment by mtrejo30** [comment]
Se elimino la columna estaba repetida

**Comment by edgar1090** [comment]
Se elimina columna de centro
Escenario Satisfactorio
