### ISSUE TITLE
Exitencias - Liberar Doc. Inventario

### ISSUE THREAD

**Issue by GabyBere** [almacs/Pretoria#44]
1. Muestra etiqueta Incorrecta
2. No muestra No. Doc Inventario.

![image](https://cloud.githubusercontent.com/assets/11563662/6854314/184044ac-d3b6-11e4-8278-e68a6ace2bba.png)

**Comment by mtrejo30** [comment]
Modificación en SP

**Comment by GabyBere** [comment]
Falta la etiqueta

**Comment by GabyBere** [comment]
Resultado: Satisfactorio

![image](https://cloud.githubusercontent.com/assets/11563662/6922695/579f7794-d78a-11e4-8ce4-0717fd80e6e6.png)
