### ISSUE TITLE
Captura de Produccion Atomizado - Valor del contador al resetearse

### ISSUE THREAD

**Issue by edgar1090** [almacs/Pretoria#45]
Ruta: Captura - Produccion - Barbotina y Polvo Atomizado

Al reseterase el campo Contador Final Caudaliment solo debe permitir capturar el valor menor o igual a 288000 lo cual esta correcto no deja ninguna cantidad mayor a esa a excepcion de una la cual corresponde al numero exacto del valor del contador final del turno anterior.

**Comment by mtrejo30** [comment]
Validar el cambio

**Comment by mtrejo30** [comment]
Volver a validar se encontró detalle en el edit

**Comment by edgar1090** [comment]
Escenario Satisfactorio
