### ISSUE TITLE
Justificacion Tiempo Muertos - Boton editar desaparece

### ISSUE THREAD

**Issue by edgar1090** [almacs/Pretoria#46]
Ruta: Captura - Producción - Tiempo Muertos

Al momento de seleccionar un registro para editarlo desaparece el botón de edit
(Al parecer se desplaza a la derecha en la pantalla y ya no permite verlo)

**Comment by mtrejo30** [comment]
Por cuestión de funcionalidad especifica y en base a lo consultado con Luis queda tal cual.

el tiempo pendiente de justificar, solo lo puedes justificar una vez
cuando justificas el tiempo (o parte del mismo), el registro que haces ya no lo puedes modificar
entonces, si tienes un paro de 40 minutos
y lo seleccionas para editar, puedes justificar 20 minutos. ese "justificante" se vuelve de solo lectura, por decirlo asi
pero puedes "editar" los 20 minutos restantes
