### ISSUE TITLE
R107 Con Pastas

### ISSUE THREAD

**Issue by almacs** [almacs/Pretoria#7]
![image](https://cloud.githubusercontent.com/assets/9678980/6743261/2fcd6d1a-ce5d-11e4-95e1-28ab52e333a2.png)

**Comment by GabyBere** [comment]
Resultado: Satisfactorio.

![image](https://cloud.githubusercontent.com/assets/11563662/6870463/e490dae8-d461-11e4-8352-a6adca2e4345.png)
