### ISSUE TITLE
Cosumo de Energeticos

### ISSUE THREAD

**Issue by almacs** [almacs/Pretoria#8]
No se encuentra la tabla de Consumo Energético
![image](https://cloud.githubusercontent.com/assets/11563662/6755575/cb980016-cee9-11e4-9cca-926e28ba306b.png)

**Comment by GabyBere** [comment]
En Producción si se encuentra la tabla de Consumo Energético
![image](https://cloud.githubusercontent.com/assets/11563662/6755681/89d3d848-ceea-11e4-8703-210fcb63b64f.png)

**Comment by GabyBere** [comment]
No se encuentra la tabla de consumo energético
![image](https://cloud.githubusercontent.com/assets/11563662/6784208/01d0aa64-d144-11e4-829b-e2bb5479ddeb.png)

**Comment by GabyBere** [comment]
No se encuentra la tabla de consumo energético
![image](https://cloud.githubusercontent.com/assets/11563662/6784208/01d0aa64-d144-11e4-829b-e2bb5479ddeb.png)

**Comment by mtrejo30** [comment]
Volver a validar

**Comment by GabyBere** [comment]
Resultado: Exitoso.

![image](https://cloud.githubusercontent.com/assets/11563662/6816183/3f6b7162-d255-11e4-9c52-0511a4deac57.png)
